"""Public constants for the PragmaGraph semantic alpha contract."""

from __future__ import annotations

SCHEMA_VERSION = "pragmagraph.snapshot.v1alpha1"
INDEXER_VERSION = "pragmagraph.indexer.v1alpha1"

CAPABILITY_QUERY = "query"
CAPABILITY_NEIGHBORHOOD = "neighborhood"
CAPABILITY_PATH = "path"
CAPABILITY_HEALTH = "health"
CAPABILITY_REFRESH = "refresh"
CAPABILITY_CITATIONS = "citations"
CAPABILITY_PROVENANCE = "provenance"
CAPABILITY_EXPLAIN = "explain"
CAPABILITY_SECURITY_POLICY = "security_policy"
CAPABILITY_GIT_HISTORY = "git_history"

CAPABILITIES = frozenset(
    {
        CAPABILITY_QUERY,
        CAPABILITY_NEIGHBORHOOD,
        CAPABILITY_PATH,
        CAPABILITY_HEALTH,
        CAPABILITY_REFRESH,
        CAPABILITY_CITATIONS,
        CAPABILITY_PROVENANCE,
        CAPABILITY_EXPLAIN,
        CAPABILITY_SECURITY_POLICY,
        CAPABILITY_GIT_HISTORY,
    }
)

NODE_PROJECT = "project"
NODE_DIRECTORY = "directory"
NODE_FILE = "file"
NODE_DOC_SECTION = "doc_section"
NODE_PYTHON_SYMBOL = "python_symbol"
NODE_PYTHON_MODULE = "python_module"
NODE_PYTHON_CLASS = "python_class"
NODE_PYTHON_FUNCTION = "python_function"
NODE_PYTHON_METHOD = "python_method"
NODE_SCRIPT_MODULE = "script_module"
NODE_SCRIPT_FUNCTION = "script_function"
NODE_SCRIPT_CLASS = "script_class"
NODE_SCRIPT_EXPORT = "script_export"
NODE_IMPORT = "import"
NODE_CONFIG = "config"
NODE_CONFIG_KEY = "config_key"
NODE_GIT_COMMIT = "git_commit"
NODE_GIT_CHANGED_PATH = "git_changed_path"

NODE_KINDS = frozenset(
    {
        NODE_PROJECT,
        NODE_DIRECTORY,
        NODE_FILE,
        NODE_DOC_SECTION,
        NODE_PYTHON_SYMBOL,
        NODE_PYTHON_MODULE,
        NODE_PYTHON_CLASS,
        NODE_PYTHON_FUNCTION,
        NODE_PYTHON_METHOD,
        NODE_SCRIPT_MODULE,
        NODE_SCRIPT_FUNCTION,
        NODE_SCRIPT_CLASS,
        NODE_SCRIPT_EXPORT,
        NODE_IMPORT,
        NODE_CONFIG,
        NODE_CONFIG_KEY,
        NODE_GIT_COMMIT,
        NODE_GIT_CHANGED_PATH,
    }
)

EDGE_CONTAINS = "contains"
EDGE_DEFINES = "defines"
EDGE_IMPORTS = "imports"
EDGE_MENTIONS = "mentions"
EDGE_REFERENCES_SECTION = "references_section"
EDGE_CALLS = "calls"
EDGE_INHERITS = "inherits"
EDGE_PARENT_SYMBOL = "parent_symbol"
EDGE_REFERENCES_DOC = "references_doc"
EDGE_HAS_KEY = "has_key"
EDGE_DEPENDS_ON = "depends_on"
EDGE_GIT_PARENT = "git_parent"
EDGE_GIT_CHANGES_PATH = "git_changes_path"
EDGE_GIT_TOUCHES = "git_touches"

EDGE_KINDS = frozenset(
    {
        EDGE_CONTAINS,
        EDGE_DEFINES,
        EDGE_IMPORTS,
        EDGE_MENTIONS,
        EDGE_REFERENCES_SECTION,
        EDGE_CALLS,
        EDGE_INHERITS,
        EDGE_PARENT_SYMBOL,
        EDGE_REFERENCES_DOC,
        EDGE_HAS_KEY,
        EDGE_DEPENDS_ON,
        EDGE_GIT_PARENT,
        EDGE_GIT_CHANGES_PATH,
        EDGE_GIT_TOUCHES,
    }
)

__all__ = [
    "CAPABILITIES",
    "CAPABILITY_CITATIONS",
    "CAPABILITY_EXPLAIN",
    "CAPABILITY_GIT_HISTORY",
    "CAPABILITY_HEALTH",
    "CAPABILITY_NEIGHBORHOOD",
    "CAPABILITY_PATH",
    "CAPABILITY_PROVENANCE",
    "CAPABILITY_QUERY",
    "CAPABILITY_REFRESH",
    "CAPABILITY_SECURITY_POLICY",
    "EDGE_CALLS",
    "EDGE_CONTAINS",
    "EDGE_DEPENDS_ON",
    "EDGE_DEFINES",
    "EDGE_GIT_CHANGES_PATH",
    "EDGE_GIT_PARENT",
    "EDGE_GIT_TOUCHES",
    "EDGE_HAS_KEY",
    "EDGE_INHERITS",
    "EDGE_IMPORTS",
    "EDGE_KINDS",
    "EDGE_MENTIONS",
    "EDGE_PARENT_SYMBOL",
    "EDGE_REFERENCES_DOC",
    "EDGE_REFERENCES_SECTION",
    "INDEXER_VERSION",
    "NODE_CONFIG",
    "NODE_CONFIG_KEY",
    "NODE_DIRECTORY",
    "NODE_DOC_SECTION",
    "NODE_FILE",
    "NODE_GIT_CHANGED_PATH",
    "NODE_GIT_COMMIT",
    "NODE_IMPORT",
    "NODE_KINDS",
    "NODE_PROJECT",
    "NODE_PYTHON_CLASS",
    "NODE_PYTHON_FUNCTION",
    "NODE_PYTHON_METHOD",
    "NODE_PYTHON_MODULE",
    "NODE_PYTHON_SYMBOL",
    "NODE_SCRIPT_CLASS",
    "NODE_SCRIPT_EXPORT",
    "NODE_SCRIPT_FUNCTION",
    "NODE_SCRIPT_MODULE",
    "SCHEMA_VERSION",
]
