"""Public constants for the PragmaGraph semantic alpha contract."""

from __future__ import annotations

SCHEMA_VERSION = "pragmagraph.snapshot.v1alpha1"
INDEXER_VERSION = "pragmagraph.indexer.v1alpha2"

CAPABILITY_QUERY = "query"
CAPABILITY_NEIGHBORHOOD = "neighborhood"
CAPABILITY_PATH = "path"
CAPABILITY_HEALTH = "health"
CAPABILITY_REFRESH = "refresh"
CAPABILITY_CITATIONS = "citations"
CAPABILITY_PROVENANCE = "provenance"
CAPABILITY_EXPLAIN = "explain"
CAPABILITY_SECURITY_POLICY = "security_policy"
CAPABILITY_GIT_HISTORY = "git_history"
CAPABILITY_QUERY_PAGINATION = "query_pagination"
CAPABILITY_MULTI_ROOT = "multi_root"
CAPABILITY_PRECISE_INTERCHANGE = "precise_interchange"
CAPABILITY_ARTIFACT_FACTS = "artifact_facts"
CAPABILITY_CI_DELTA = "ci_delta"
CAPABILITY_MCP_RESOURCES = "mcp_resources"
CAPABILITY_EXPORT_REDACTION = "export_redaction"

CAPABILITIES = frozenset(
    {
        CAPABILITY_QUERY,
        CAPABILITY_NEIGHBORHOOD,
        CAPABILITY_PATH,
        CAPABILITY_HEALTH,
        CAPABILITY_REFRESH,
        CAPABILITY_CITATIONS,
        CAPABILITY_PROVENANCE,
        CAPABILITY_EXPLAIN,
        CAPABILITY_SECURITY_POLICY,
        CAPABILITY_GIT_HISTORY,
        CAPABILITY_QUERY_PAGINATION,
        CAPABILITY_MULTI_ROOT,
        CAPABILITY_PRECISE_INTERCHANGE,
        CAPABILITY_ARTIFACT_FACTS,
        CAPABILITY_CI_DELTA,
        CAPABILITY_MCP_RESOURCES,
        CAPABILITY_EXPORT_REDACTION,
    }
)

NODE_PROJECT = "project"
NODE_SYMBOL = "symbol"
NODE_WORKSPACE = "workspace"
NODE_DIRECTORY = "directory"
NODE_FILE = "file"
NODE_DOC_SECTION = "doc_section"
NODE_PYTHON_SYMBOL = "python_symbol"
NODE_PYTHON_MODULE = "python_module"
NODE_PYTHON_CLASS = "python_class"
NODE_PYTHON_FUNCTION = "python_function"
NODE_PYTHON_METHOD = "python_method"
NODE_SCRIPT_MODULE = "script_module"
NODE_SCRIPT_FUNCTION = "script_function"
NODE_SCRIPT_CLASS = "script_class"
NODE_SCRIPT_EXPORT = "script_export"
NODE_IMPORT = "import"
NODE_CONFIG = "config"
NODE_CONFIG_KEY = "config_key"
NODE_GIT_COMMIT = "git_commit"
NODE_GIT_CHANGED_PATH = "git_changed_path"
NODE_API_ENDPOINT = "api_endpoint"
NODE_API_SCHEMA = "api_schema"
NODE_PROTO_MESSAGE = "proto_message"
NODE_PROTO_SERVICE = "proto_service"
NODE_PROTO_RPC = "proto_rpc"
NODE_SQL_TABLE = "sql_table"
NODE_TERRAFORM_BLOCK = "terraform_block"
NODE_CI_JOB = "ci_job"
NODE_DEPENDENCY_DECLARATION = "dependency_declaration"
NODE_DEPENDENCY_RESOLUTION = "dependency_resolution"

NODE_KINDS = frozenset(
    {
        NODE_PROJECT,
        NODE_SYMBOL,
        NODE_WORKSPACE,
        NODE_DIRECTORY,
        NODE_FILE,
        NODE_DOC_SECTION,
        NODE_PYTHON_SYMBOL,
        NODE_PYTHON_MODULE,
        NODE_PYTHON_CLASS,
        NODE_PYTHON_FUNCTION,
        NODE_PYTHON_METHOD,
        NODE_SCRIPT_MODULE,
        NODE_SCRIPT_FUNCTION,
        NODE_SCRIPT_CLASS,
        NODE_SCRIPT_EXPORT,
        NODE_IMPORT,
        NODE_CONFIG,
        NODE_CONFIG_KEY,
        NODE_GIT_COMMIT,
        NODE_GIT_CHANGED_PATH,
        NODE_API_ENDPOINT,
        NODE_API_SCHEMA,
        NODE_PROTO_MESSAGE,
        NODE_PROTO_SERVICE,
        NODE_PROTO_RPC,
        NODE_SQL_TABLE,
        NODE_TERRAFORM_BLOCK,
        NODE_CI_JOB,
        NODE_DEPENDENCY_DECLARATION,
        NODE_DEPENDENCY_RESOLUTION,
    }
)

EDGE_CONTAINS = "contains"
EDGE_DEFINES = "defines"
EDGE_IMPORTS = "imports"
EDGE_MENTIONS = "mentions"
EDGE_REFERENCES_SECTION = "references_section"
EDGE_CALLS = "calls"
EDGE_INHERITS = "inherits"
EDGE_PARENT_SYMBOL = "parent_symbol"
EDGE_REFERENCES_DOC = "references_doc"
EDGE_HAS_KEY = "has_key"
EDGE_DEPENDS_ON = "depends_on"
EDGE_GIT_PARENT = "git_parent"
EDGE_GIT_CHANGES_PATH = "git_changes_path"
EDGE_GIT_TOUCHES = "git_touches"
EDGE_RESOLVES_TO = "resolves_to"

EDGE_KINDS = frozenset(
    {
        EDGE_CONTAINS,
        EDGE_DEFINES,
        EDGE_IMPORTS,
        EDGE_MENTIONS,
        EDGE_REFERENCES_SECTION,
        EDGE_CALLS,
        EDGE_INHERITS,
        EDGE_PARENT_SYMBOL,
        EDGE_REFERENCES_DOC,
        EDGE_HAS_KEY,
        EDGE_DEPENDS_ON,
        EDGE_GIT_PARENT,
        EDGE_GIT_CHANGES_PATH,
        EDGE_GIT_TOUCHES,
        EDGE_RESOLVES_TO,
    }
)

# Evidence-bridge freshness states (PGSIM-01). Package-owned *structural* status
# for one cited evidence reference — never an LLM judgment. See
# docs/specs/pragmagraph-self-improving-memory-evidence-bridge-spec.md.
FRESHNESS_FRESH = "fresh"
FRESHNESS_STALE = "stale"
FRESHNESS_MISSING = "missing"
FRESHNESS_CHANGED = "changed"

FRESHNESS_STATES = frozenset(
    {
        FRESHNESS_FRESH,
        FRESHNESS_STALE,
        FRESHNESS_MISSING,
        FRESHNESS_CHANGED,
    }
)

# Evidence-bridge query kinds (PGSIM-01 DTO surface; PGSIM-02 resolves them).
EVIDENCE_QUERY_SUPPORT_CANDIDATE = "support_candidate"
EVIDENCE_QUERY_VERIFY_CITATION = "verify_citation"
EVIDENCE_QUERY_RECHECK_STALENESS = "recheck_staleness"
EVIDENCE_QUERY_COLLECT_RELATED = "collect_related_evidence"

EVIDENCE_QUERY_KINDS = frozenset(
    {
        EVIDENCE_QUERY_SUPPORT_CANDIDATE,
        EVIDENCE_QUERY_VERIFY_CITATION,
        EVIDENCE_QUERY_RECHECK_STALENESS,
        EVIDENCE_QUERY_COLLECT_RELATED,
    }
)

__all__ = [
    "CAPABILITIES",
    "CAPABILITY_CITATIONS",
    "CAPABILITY_EXPLAIN",
    "CAPABILITY_GIT_HISTORY",
    "CAPABILITY_QUERY_PAGINATION",
    "CAPABILITY_MULTI_ROOT",
    "CAPABILITY_PRECISE_INTERCHANGE",
    "CAPABILITY_ARTIFACT_FACTS",
    "CAPABILITY_CI_DELTA",
    "CAPABILITY_MCP_RESOURCES",
    "CAPABILITY_EXPORT_REDACTION",
    "CAPABILITY_HEALTH",
    "CAPABILITY_NEIGHBORHOOD",
    "CAPABILITY_PATH",
    "CAPABILITY_PROVENANCE",
    "CAPABILITY_QUERY",
    "CAPABILITY_REFRESH",
    "CAPABILITY_SECURITY_POLICY",
    "EDGE_CALLS",
    "EDGE_CONTAINS",
    "EDGE_DEPENDS_ON",
    "EDGE_DEFINES",
    "EDGE_GIT_CHANGES_PATH",
    "EDGE_GIT_PARENT",
    "EDGE_GIT_TOUCHES",
    "EDGE_HAS_KEY",
    "EDGE_INHERITS",
    "EDGE_IMPORTS",
    "EDGE_KINDS",
    "EDGE_MENTIONS",
    "EDGE_PARENT_SYMBOL",
    "EDGE_REFERENCES_DOC",
    "EDGE_REFERENCES_SECTION",
    "EDGE_RESOLVES_TO",
    "EVIDENCE_QUERY_COLLECT_RELATED",
    "EVIDENCE_QUERY_KINDS",
    "EVIDENCE_QUERY_RECHECK_STALENESS",
    "EVIDENCE_QUERY_SUPPORT_CANDIDATE",
    "EVIDENCE_QUERY_VERIFY_CITATION",
    "FRESHNESS_CHANGED",
    "FRESHNESS_FRESH",
    "FRESHNESS_MISSING",
    "FRESHNESS_STALE",
    "FRESHNESS_STATES",
    "INDEXER_VERSION",
    "NODE_CONFIG",
    "NODE_CONFIG_KEY",
    "NODE_DIRECTORY",
    "NODE_DOC_SECTION",
    "NODE_FILE",
    "NODE_GIT_CHANGED_PATH",
    "NODE_GIT_COMMIT",
    "NODE_API_ENDPOINT",
    "NODE_API_SCHEMA",
    "NODE_CI_JOB",
    "NODE_DEPENDENCY_DECLARATION",
    "NODE_DEPENDENCY_RESOLUTION",
    "NODE_PROTO_MESSAGE",
    "NODE_PROTO_RPC",
    "NODE_PROTO_SERVICE",
    "NODE_SQL_TABLE",
    "NODE_TERRAFORM_BLOCK",
    "NODE_IMPORT",
    "NODE_KINDS",
    "NODE_PROJECT",
    "NODE_SYMBOL",
    "NODE_WORKSPACE",
    "NODE_PYTHON_CLASS",
    "NODE_PYTHON_FUNCTION",
    "NODE_PYTHON_METHOD",
    "NODE_PYTHON_MODULE",
    "NODE_PYTHON_SYMBOL",
    "NODE_SCRIPT_CLASS",
    "NODE_SCRIPT_EXPORT",
    "NODE_SCRIPT_FUNCTION",
    "NODE_SCRIPT_MODULE",
    "SCHEMA_VERSION",
]
