"""Standalone observed-fact graph substrate for code and document structure."""

from __future__ import annotations

from pragmagraph.adapters import index_path
from pragmagraph.contracts import CAPABILITIES, INDEXER_VERSION, SCHEMA_VERSION
from pragmagraph.bench import (
    BenchmarkMeasurement,
    BenchmarkReport,
    benchmark_root,
    render_markdown_benchmark,
)
from pragmagraph.export import render_dot, render_graph_export, render_mermaid
from pragmagraph.evidence import (
    collect_memory_evidence,
    collect_related_memory_evidence,
    evidence_ref_for_node,
    snapshot_evidence_id,
    verify_memory_evidence_ref,
    verify_memory_evidence_refs,
)
from pragmagraph.graphify import (
    GRAPHIFY_INTEROP_FORMAT,
    snapshot_from_graphify_payload,
    to_graphify_payload,
)
from pragmagraph.models import (
    GraphEdge,
    GraphNode,
    GraphSnapshot,
    HealthSummary,
    MemoryEvidenceBundle,
    MemoryEvidenceRef,
    OmittedDiagnostic,
    PathResult,
    ParserDiagnostic,
    ParserResult,
    PragmaGraphError,
    QueryExplanation,
    QueryHit,
    QueryRequest,
    QueryResult,
    RefreshManifest,
    RefreshManifestEntry,
    RefreshPathChange,
    RefreshResult,
    SnapshotStructuralDelta,
    SourceRef,
)
from pragmagraph.report import (
    GraphReport,
    GraphReportDependency,
    GraphReportFinding,
    GraphReportGitCommit,
    GraphReportNode,
    GraphReportSummary,
    build_report,
    render_markdown_report,
)
from pragmagraph.query import (
    backlinks,
    commits_touching_symbol_file,
    files_touched_by_commit,
    impact,
    recent_commits_for_path,
    reverse_dependencies,
    reverse_imports,
)
from pragmagraph.operations import (
    RefreshOperationResult,
    RefreshPlan,
    RefreshProfile,
    RefreshStatus,
    build_refresh_plan,
    build_refresh_profile,
    load_refresh_profile,
    load_refresh_status,
    refresh_status_from_result,
    run_refresh_profile,
    save_refresh_profile,
    save_refresh_status,
)
from pragmagraph.refresh import diff_snapshots, refresh_snapshot
from pragmagraph.storage import load_snapshot, save_snapshot, stable_dumps
from pragmagraph.workspace import (
    WorkspaceMetadata,
    WorkspacePaths,
    WorkspaceRefreshResult,
    WorkspaceStatusView,
    build_workspace_metadata,
    initialize_workspace,
    load_workspace_metadata,
    load_workspace_status,
    refresh_workspace,
)

__version__ = "0.0.3"

PACKAGE_STATUS = "semantic-alpha"
STABLE_IMPORT_ROOTS = (
    "pragmagraph",
    "pragmagraph.contracts",
    "pragmagraph.models",
    "pragmagraph.query",
    "pragmagraph.storage",
    "pragmagraph.adapters",
    "pragmagraph.bench",
    "pragmagraph.portability",
    "pragmagraph.parsers",
    "pragmagraph.export",
    "pragmagraph.evidence",
    "pragmagraph.graphify",
    "pragmagraph.report",
    "pragmagraph.refresh",
    "pragmagraph.operations",
    "pragmagraph.security",
    "pragmagraph.service",
    "pragmagraph.ui",
    "pragmagraph.workspace",
)

__all__ = [
    "CAPABILITIES",
    "BenchmarkMeasurement",
    "BenchmarkReport",
    "GraphEdge",
    "GraphNode",
    "GraphReport",
    "GraphReportDependency",
    "GraphReportFinding",
    "GraphReportGitCommit",
    "GraphReportNode",
    "GraphReportSummary",
    "GraphSnapshot",
    "GRAPHIFY_INTEROP_FORMAT",
    "HealthSummary",
    "INDEXER_VERSION",
    "MemoryEvidenceBundle",
    "MemoryEvidenceRef",
    "OmittedDiagnostic",
    "PACKAGE_STATUS",
    "PathResult",
    "ParserDiagnostic",
    "ParserResult",
    "PragmaGraphError",
    "QueryExplanation",
    "QueryHit",
    "QueryRequest",
    "QueryResult",
    "RefreshManifest",
    "RefreshManifestEntry",
    "RefreshPathChange",
    "RefreshResult",
    "SCHEMA_VERSION",
    "SnapshotStructuralDelta",
    "STABLE_IMPORT_ROOTS",
    "SourceRef",
    "__version__",
    "backlinks",
    "commits_touching_symbol_file",
    "collect_memory_evidence",
    "collect_related_memory_evidence",
    "files_touched_by_commit",
    "benchmark_root",
    "build_report",
    "diff_snapshots",
    "evidence_ref_for_node",
    "impact",
    "index_path",
    "initialize_workspace",
    "load_workspace_metadata",
    "load_workspace_status",
    "recent_commits_for_path",
    "load_snapshot",
    "render_dot",
    "render_graph_export",
    "render_markdown_benchmark",
    "render_mermaid",
    "render_markdown_report",
    "RefreshOperationResult",
    "RefreshPlan",
    "RefreshProfile",
    "RefreshStatus",
    "build_refresh_plan",
    "build_refresh_profile",
    "refresh_snapshot",
    "refresh_status_from_result",
    "refresh_workspace",
    "reverse_dependencies",
    "reverse_imports",
    "load_refresh_profile",
    "load_refresh_status",
    "run_refresh_profile",
    "save_snapshot",
    "save_refresh_profile",
    "save_refresh_status",
    "snapshot_evidence_id",
    "snapshot_from_graphify_payload",
    "stable_dumps",
    "to_graphify_payload",
    "verify_memory_evidence_ref",
    "verify_memory_evidence_refs",
    "WorkspaceMetadata",
    "WorkspacePaths",
    "WorkspaceRefreshResult",
    "WorkspaceStatusView",
    "build_workspace_metadata",
]
