"""Standalone observed-fact graph substrate for code and document structure."""

from __future__ import annotations

from pragmagraph.adapters import index_path
from pragmagraph.contracts import CAPABILITIES, INDEXER_VERSION, SCHEMA_VERSION
from pragmagraph.bench import (
    BenchmarkMeasurement,
    BenchmarkReport,
    benchmark_root,
    render_markdown_benchmark,
)
from pragmagraph.certification import (
    CertificationPack,
    PrivacyProfile,
    build_certification_pack,
    build_privacy_profile,
)
from pragmagraph.docgraph import (
    DocGraphSummary,
    DocMentionCandidate,
    DocReferenceTarget,
    build_doc_graph_summary,
    render_markdown_doc_graph,
)
from pragmagraph.export import render_dot, render_graph_export, render_mermaid
from pragmagraph.evidence import (
    collect_memory_evidence,
    collect_related_memory_evidence,
    evidence_ref_for_node,
    snapshot_evidence_id,
    verify_memory_evidence_ref,
    verify_memory_evidence_refs,
)
from pragmagraph.graphify import (
    GRAPHIFY_INTEROP_FORMAT,
    snapshot_from_graphify_payload,
    to_graphify_payload,
)
from pragmagraph.interchange import (
    INTERCHANGE_FORMAT,
    InterchangeBundle,
    ReferenceRecord,
    SymbolRecord,
    build_symbol_reference_bundle,
)
from pragmagraph.lineage import GitLineage, GitLineageEntry, build_git_lineage
from pragmagraph.models import (
    GraphEdge,
    GraphNode,
    GraphSnapshot,
    HealthSummary,
    MemoryEvidenceBundle,
    MemoryEvidenceRef,
    OmittedDiagnostic,
    PathResult,
    ParserDiagnostic,
    ParserResult,
    PragmaGraphError,
    QueryExplanation,
    QueryHit,
    QueryRequest,
    QueryResult,
    RefreshManifest,
    RefreshManifestEntry,
    RefreshPathChange,
    RefreshResult,
    SnapshotStructuralDelta,
    SourceRef,
)
from pragmagraph.navigation import (
    RepoMap,
    RepoMapSection,
    build_repo_map,
    render_compact_handoff,
    render_markdown_repo_map,
)
from pragmagraph.parser_support import (
    ParserFamilySupport,
    build_parser_support_matrix,
)
from pragmagraph.planner import QueryPlanEvidence, explain_query_plan
from pragmagraph.report import (
    GraphReport,
    GraphReportDependency,
    GraphReportFinding,
    GraphReportGitCommit,
    GraphReportNode,
    GraphReportSummary,
    build_report,
    render_markdown_report,
)
from pragmagraph.topology import (
    TopologyComponent,
    TopologyNode,
    TopologySummary,
    build_topology_summary,
    render_markdown_topology,
)
from pragmagraph.viewer import (
    VIEWER_ENVELOPE_SCHEMA_VERSION,
    VIEWER_FIXTURE_SCENARIOS,
    ViewerGraphEnvelope,
    build_viewer_envelope,
    build_viewer_fixture_envelope,
    explain_omitted,
    load_viewer_envelope,
    viewer_cluster,
    viewer_cluster_nodes,
    viewer_content,
    viewer_delta,
    viewer_envelope_neighborhood,
    viewer_envelope_path,
    viewer_neighborhood,
    viewer_path,
    write_viewer_envelope,
)
from pragmagraph.query import (
    backlinks,
    commits_touching_symbol_file,
    files_touched_by_commit,
    impact,
    recent_commits_for_path,
    reverse_dependencies,
    reverse_imports,
)
from pragmagraph.operations import (
    RefreshOperationResult,
    RefreshPlan,
    RefreshProfile,
    RefreshStatus,
    build_refresh_plan,
    build_refresh_profile,
    load_refresh_profile,
    load_refresh_status,
    refresh_status_from_result,
    run_refresh_profile,
    save_refresh_profile,
    save_refresh_status,
)
from pragmagraph.refresh import diff_snapshots, refresh_snapshot
from pragmagraph.storage import load_snapshot, save_snapshot, stable_dumps
from pragmagraph.workspace import (
    CrossRepoResolutionReport,
    NamedSnapshot,
    SnapshotCompositionResult,
    WorkspaceMetadata,
    WorkspacePaths,
    WorkspaceRefreshResult,
    WorkspaceStatusView,
    build_workspace_metadata,
    compose_snapshots,
    initialize_workspace,
    load_workspace_metadata,
    load_workspace_status,
    refresh_workspace,
    save_composed_snapshot_atomic,
)

__version__ = "0.0.5"

PACKAGE_STATUS = "semantic-alpha"
STABLE_IMPORT_ROOTS = (
    "pragmagraph",
    "pragmagraph.contracts",
    "pragmagraph.models",
    "pragmagraph.query",
    "pragmagraph.storage",
    "pragmagraph.adapters",
    "pragmagraph.bench",
    "pragmagraph.portability",
    "pragmagraph.parsers",
    "pragmagraph.export",
    "pragmagraph.evidence",
    "pragmagraph.graphify",
    "pragmagraph.report",
    "pragmagraph.refresh",
    "pragmagraph.operations",
    "pragmagraph.security",
    "pragmagraph.service",
    "pragmagraph.ui",
    "pragmagraph.workspace",
    "pragmagraph.navigation",
    "pragmagraph.interchange",
    "pragmagraph.topology",
    "pragmagraph.docgraph",
    "pragmagraph.planner",
    "pragmagraph.certification",
    "pragmagraph.lineage",
    "pragmagraph.parser_support",
    "pragmagraph.viewer",
)

__all__ = [
    "CAPABILITIES",
    "BenchmarkMeasurement",
    "BenchmarkReport",
    "CertificationPack",
    "CrossRepoResolutionReport",
    "DocGraphSummary",
    "DocMentionCandidate",
    "DocReferenceTarget",
    "GraphEdge",
    "GraphNode",
    "GraphReport",
    "GraphReportDependency",
    "GraphReportFinding",
    "GraphReportGitCommit",
    "GraphReportNode",
    "GraphReportSummary",
    "GraphSnapshot",
    "GRAPHIFY_INTEROP_FORMAT",
    "GitLineage",
    "GitLineageEntry",
    "HealthSummary",
    "INDEXER_VERSION",
    "INTERCHANGE_FORMAT",
    "InterchangeBundle",
    "MemoryEvidenceBundle",
    "MemoryEvidenceRef",
    "NamedSnapshot",
    "OmittedDiagnostic",
    "PACKAGE_STATUS",
    "PathResult",
    "ParserFamilySupport",
    "ParserDiagnostic",
    "ParserResult",
    "PragmaGraphError",
    "PrivacyProfile",
    "QueryExplanation",
    "QueryHit",
    "QueryPlanEvidence",
    "QueryRequest",
    "QueryResult",
    "ReferenceRecord",
    "RefreshManifest",
    "RefreshManifestEntry",
    "RefreshPathChange",
    "RefreshResult",
    "RepoMap",
    "RepoMapSection",
    "SCHEMA_VERSION",
    "SnapshotStructuralDelta",
    "SnapshotCompositionResult",
    "STABLE_IMPORT_ROOTS",
    "SourceRef",
    "SymbolRecord",
    "TopologyComponent",
    "TopologyNode",
    "TopologySummary",
    "VIEWER_ENVELOPE_SCHEMA_VERSION",
    "VIEWER_FIXTURE_SCENARIOS",
    "ViewerGraphEnvelope",
    "__version__",
    "backlinks",
    "commits_touching_symbol_file",
    "collect_memory_evidence",
    "collect_related_memory_evidence",
    "compose_snapshots",
    "files_touched_by_commit",
    "benchmark_root",
    "build_certification_pack",
    "build_doc_graph_summary",
    "build_git_lineage",
    "build_parser_support_matrix",
    "build_privacy_profile",
    "build_report",
    "build_repo_map",
    "build_symbol_reference_bundle",
    "build_topology_summary",
    "build_viewer_envelope",
    "build_viewer_fixture_envelope",
    "diff_snapshots",
    "evidence_ref_for_node",
    "explain_omitted",
    "explain_query_plan",
    "impact",
    "index_path",
    "initialize_workspace",
    "load_workspace_metadata",
    "load_workspace_status",
    "load_viewer_envelope",
    "recent_commits_for_path",
    "load_snapshot",
    "render_dot",
    "render_graph_export",
    "render_compact_handoff",
    "render_markdown_benchmark",
    "render_markdown_doc_graph",
    "render_markdown_repo_map",
    "render_markdown_topology",
    "render_mermaid",
    "render_markdown_report",
    "RefreshOperationResult",
    "RefreshPlan",
    "RefreshProfile",
    "RefreshStatus",
    "build_refresh_plan",
    "build_refresh_profile",
    "refresh_snapshot",
    "refresh_status_from_result",
    "refresh_workspace",
    "reverse_dependencies",
    "reverse_imports",
    "load_refresh_profile",
    "load_refresh_status",
    "run_refresh_profile",
    "save_snapshot",
    "save_composed_snapshot_atomic",
    "save_refresh_profile",
    "save_refresh_status",
    "snapshot_evidence_id",
    "snapshot_from_graphify_payload",
    "stable_dumps",
    "to_graphify_payload",
    "verify_memory_evidence_ref",
    "verify_memory_evidence_refs",
    "viewer_cluster",
    "viewer_cluster_nodes",
    "viewer_content",
    "viewer_delta",
    "viewer_envelope_neighborhood",
    "viewer_envelope_path",
    "viewer_neighborhood",
    "viewer_path",
    "WorkspaceMetadata",
    "WorkspacePaths",
    "WorkspaceRefreshResult",
    "WorkspaceStatusView",
    "build_workspace_metadata",
    "write_viewer_envelope",
]
